config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: :true
  validates :address, presence: :true
  validates :price_per_night, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    # *Strong params*: You need to *whitelist* what can be u # Never trust user data!
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Edit flat</h1>

<%= simple_form_for(@flat) do |f| %> <%
  if @flat.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @flat.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.button :submit, class: "btn btn-primary"%>
<% end %>

<%= link_to "Go Back", flats_path %>

app/views/flats/index.html.erb
<h1>All our Flats (<%= Flat.count %>)</h1>

<ul>
    <div class="container">
      <div class="row">
        <% @flats.each do |flat| %>
          <div class="col-xs-12 col-sm-4">
            <div class="card">
              <div class="card-picture" style="background-image: linear-gradient(-225deg, rgba(102, 67, 181, 0.1) 0%, rgba(102, 67, 181, 0.1) 50%), url('https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200')">
                <div class="card-details-numerics">
                  <p class="number_of_guests">
                    <i class="fa fa-users" aria-hidden="true"></i> <%= flat.number_of_guests %>
                  </p>
                  <p class="price">
                    <i class="fa fa-eur" aria-hidden="true"></i> <%= flat.price_per_night %>
                  </p>
                </div>
              </div>
              <div class="card-details">
                <h4><%= flat.name %></h4>
                <h5><%= flat.address %></h5>
              </div>
              <div class="card-footer">
                <div class="fa-green">
                  <%= link_to '<i class="fa fa-info" aria-hidden="true"></i> More info'.html_safe, flat_path(flat)%>
                </div>
                <div class="fa-blue">
                  <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i> Edit'.html_safe, edit_flat_path(flat)%>
                </div>
                <div class="fa-red">
                <%= link_to '<i class="fa fa-trash" aria-hidden="true"></i> Delete'.html_safe, flat_path(flat),
                    method: :delete,
                    data: { confirm: "Are you sure you want to delete this flat?" }%>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
</ul>

app/views/flats/new.html.erb
<h1>Add a new flat</h1>

<%= simple_form_for(@flat) do |f| %> <%
  if @flat.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @flat.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.button :submit, class: "btn btn-primary"%>
<% end %>

<%= link_to "Go Back", flats_path %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>
<h2><%= @flat.address %></h2>

<h3><%= @flat.description %></h3>

<p><%= @flat.price_per_night %></p>
<p><%= @flat.number_of_guests %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to "AirBnb", flats_path %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to "Add Flat", new_flat_path, class: "btn btn-primary"%>
  </div>
</div>